reporting-app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :activity_report_application_forms, except: [ :index ] do
    resources :activities, only: [ :show, :new, :create, :edit, :update, :destroy ] do
      member do
        get :documents
        post :upload_documents
      end
    end
    member do
      get :review
      post :submit
    end
  end

  resources :exemption_application_forms, except: [ :index ] do
    member do
      get :review
      post :submit
      get :documents
      post :upload_documents
    end
  end

  get "/dashboard", to: "dashboard#index"

  scope path: "/api", as: :api, defaults: { format: :json } do
    mount OasRails::Engine, at: "/docs", defaults: { format: :html }

    # can add other mixed API/UI controllers here
  end
  namespace :api do
    resources :certifications, only: [ :create, :show ]
    get "health" => "healthcheck#index"
  end

  scope path: "/staff" do
    resources :members, only: [ :index, :show ] do
      collection do
        get :search
        post :search
      end
    end

    resources :certifications

    resources :certification_cases, only: [ :index, :show ] do
      collection do
        get :closed
      end

      member do
        get :tasks
        get :documents
        get :notes
      end
    end

    resources :tasks, only: [ :index, :show, :update ] do
      collection do
        post :pick_up_next_task
      end

      member do
        patch :assign
      end
    end

    resources :information_requests, controller: "information_requests", only: [ :show ]

    resources :review_activity_report_tasks, only: [ :update ] do
      member do
        get :request_information
        post :create_information_request
      end
    end

    resources :review_exemption_claim_tasks, only: [ :update ] do
      member do
        get :request_information
        post :create_information_request
      end
    end
  end

  get "/staff", to: "staff#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "health" => "rails/health#show", as: :rails_health_check
  # Keep the default /up rails endpoint.
  get "up" => "rails/health#show"

  mount Lookbook::Engine, at: "/lookbook" if ENV["ENABLE_LOOKBOOK"].present?

  # Support locale prefixes for these routes:
  localized do
    # Defines the root path route ("/")
    root "home#index"

    # Session management
    devise_for :users, controllers: { sessions: "users/sessions" }
    devise_scope :user do
      get "sessions/challenge" => "users/sessions#challenge", as: :session_challenge
      post "sessions/challenge" => "users/sessions#respond_to_challenge", as: :respond_to_session_challenge
    end

    # Registration and account management
    namespace :users do
      resources :registrations, only: [ :create ]
      get "registrations" => "registrations#new", as: :new_registration

      resources :mfa, only: [ :new, :create ]
      get "mfa/preference" => "mfa#preference", as: :mfa_preference
      post "mfa/preference" => "mfa#update_preference", as: :update_mfa_preference
      delete "mfa" => "mfa#destroy", as: :disable_mfa

      get "forgot-password" => "passwords#forgot"
      post "forgot-password" => "passwords#send_reset_password_instructions"
      get "reset-password" => "passwords#reset"
      post "reset-password" => "passwords#confirm_reset"

      get "verify-account" => "registrations#new_account_verification"
      post "verify-account" => "registrations#create_account_verification"
      post "resend-verification" => "registrations#resend_verification_code"

      get "account" => "accounts#edit"
      patch "account/email" => "accounts#update_email"
    end

    # Development-only sandbox
    namespace :dev do
      get "sandbox"
      post "send_email"
    end
  end

  # Demo tools
  get "/demo", to: "demo#index"
  namespace :demo do
    resources :certifications, only: [ :new, :create ]
  end
end

reporting-app/app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  include Strata::Attributes

  has_many_attached :supporting_documents

  default_scope { with_attached_supporting_documents }

  strata_attribute :month, :date
  strata_attribute :hours, :decimal
  strata_attribute :name, :string

  validates :name, presence: true
  validates :hours, presence: true, numericality: { greater_than: 0 }
end

reporting-app/app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity_report_application_form
  before_action :set_activity, only: %i[ show edit update documents upload_documents destroy ]

  # GET /activities/1 or /activities/1.json
  def show
    authorize @activity_report_application_form
  end

  # GET /activities/new
  def new
    @activity = @activity_report_application_form.activities.build
    authorize @activity_report_application_form, :edit?
  end

  # GET /activities/1/edit
  def edit
    authorize @activity_report_application_form, :edit?
  end

  # GET /activities/1/documents
  def documents
    authorize @activity_report_application_form, :edit?
  end

  # GET /activities/1/upload_documents
  def upload_documents
    authorize @activity_report_application_form, :edit?

    supporting_documents = params.require(:activity).permit(supporting_documents: [])[:supporting_documents]
    @activity.supporting_documents.attach(supporting_documents)

    respond_to do |format|
      if @activity_report_application_form.save
        format.html { redirect_to documents_activity_report_application_form_activity_path(@activity_report_application_form, @activity) }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /activities or /activities.json
  def create
    authorize @activity_report_application_form, :update?

    @activity = @activity_report_application_form.activities.build(activity_params)

    respond_to do |format|
      if @activity_report_application_form.save
        format.html { redirect_to documents_activity_report_application_form_activity_path(@activity_report_application_form, @activity) }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    authorize @activity_report_application_form, :update?

    @activity.attributes = activity_params

    respond_to do |format|
      if @activity_report_application_form.save
        format.html { redirect_to documents_activity_report_application_form_activity_path(@activity_report_application_form, @activity) }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    authorize @activity_report_application_form, :update?

    @activity_report_application_form.activities = @activity_report_application_form.activities.reject { |activity| activity.id == params[:id] }
    @activity_report_application_form.save!

    respond_to do |format|
      format.html { redirect_to activity_report_application_form_path(@activity_report_application_form), status: :see_other, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = @activity_report_application_form.activities_by_id[params[:id]]
    end

    def set_activity_report_application_form
      @activity_report_application_form = ActivityReportApplicationForm.find(params[:activity_report_application_form_id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:month, :hours, :name)
    end
end

reporting-app/app/views/activities/_activity.html.erb
<h2>Month</h2>
<p><%= activity.month.strftime("%B %Y") %></p>

<h2>Employer name</h2>
<p><%= activity.name %></p>

<h2>Hours</h2>
<p><%= activity.hours %></p>

<%= render "application/supporting_documents", 
    model: activity %>

reporting-app/app/views/activities/_form.html.erb
<%= strata_form_with(model: [certification, activity_report_application_form, activity]) do |f| %>
  <%= f.text_field :name, label: t(".name") %>

  <%= f.select :month,
    6.times.map { |i|
      date = (Date.today - i.months).beginning_of_month
      [date.strftime("%B %Y"), date]
    }, { prompt: "- Select -" }
  %>
  
  <%= f.text_field :hours, inputmode: "decimal" %>
  
  <%= f.submit t(".continue"), big: true %>
<% end %>

reporting-app/app/views/activities/documents.html.erb
<%= render "application/upload_supporting_documents",
  model: @activity,
  url: upload_documents_certification_activity_report_application_form_activity_path(@certification, @activity_report_application_form, @activity) %>

<%= link_to t("supporting_documents.continue"), [@certification, @activity_report_application_form], class: "usa-button usa-button--outline margin-top-4" %>

reporting-app/app/views/activities/edit.html.erb
<% content_for :title, t(".title") %>

<%= link_to t(".back"), certification_activity_report_application_form_path(@certification, @activity_report_application_form) %>

<h1><%= t(".title") %></h1>

<%= render "form", activity_report_application_form: @activity_report_application_form, activity: @activity, certification: @certification %>

reporting-app/app/views/activities/new.html.erb
<% content_for :title, t(".title") %>

<%= link_to t(".back"), certification_activity_report_application_form_path(@certification, @activity_report_application_form) %>

<h1><%= t(".title") %></h1>

<%= render "form", activity_report_application_form: @activity_report_application_form, activity: @activity, certification: @certification %>

reporting-app/app/views/activities/show.html.erb
<% content_for :title, t(".title") %>

<%= link_to t(".back"), certification_activity_report_application_form_path(@certification, @activity_report_application_form) %>

<h1><%= t(".title.work", name: @activity.name) %></h1>

<%= render @activity %>

<ul class="usa-button-group margin-top-4">
  <li class="usa-button-group__item">
    <%= link_to t(".edit"), edit_certification_activity_report_application_form_activity_path(@certification, @activity_report_application_form, @activity), class: class_names("usa-button") %>
  </li>
  <li class="usa-button-group__item">
    <%= strata_form_with(model: [@certification, @activity_report_application_form, @activity], method: :delete, html: { class: "display-inline-block" }) do |f| %>
      <%= f.submit t(".destroy"), class: "usa-button--outline" %>
    <% end %>
  </li>
</ul>