reporting-app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :activity_report_application_forms, except: [ :index ] do
    resources :activities, only: [ :show, :new, :create, :edit, :update, :destroy ] do
      member do
        get :documents
        post :upload_documents
      end
    end
    member do
      get :review
      post :submit
    end
  end

  resources :exemption_application_forms, except: [ :index ] do
    member do
      get :review
      post :submit
      get :documents
      post :upload_documents
    end
  end

  get "/dashboard", to: "dashboard#index"

  scope path: "/api", as: :api, defaults: { format: :json } do
    mount OasRails::Engine, at: "/docs", defaults: { format: :html }

    # can add other mixed API/UI controllers here
  end
  namespace :api do
    resources :certifications, only: [ :create, :show ]
    get "health" => "healthcheck#index"
  end

  scope path: "/staff" do
    resources :members, only: [ :index, :show ] do
      collection do
        get :search
        post :search
      end
    end

    resources :certifications

    resources :certification_cases, only: [ :index, :show ] do
      collection do
        get :closed
      end

      member do
        get :tasks
        get :documents
        get :notes
      end
    end

    resources :tasks, only: [ :index, :show, :update ] do
      collection do
        post :pick_up_next_task
      end

      member do
        patch :assign
      end
    end

    resources :information_requests, controller: "information_requests", only: [ :show ]

    resources :review_activity_report_tasks, only: [ :update ] do
      member do
        get :request_information
        post :create_information_request
      end
    end

    resources :review_exemption_claim_tasks, only: [ :update ] do
      member do
        get :request_information
        post :create_information_request
      end
    end
  end

  get "/staff", to: "staff#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "health" => "rails/health#show", as: :rails_health_check
  # Keep the default /up rails endpoint.
  get "up" => "rails/health#show"

  mount Lookbook::Engine, at: "/lookbook" if ENV["ENABLE_LOOKBOOK"].present?

  # Support locale prefixes for these routes:
  localized do
    # Defines the root path route ("/")
    root "home#index"

    # Session management
    devise_for :users, controllers: { sessions: "users/sessions" }
    devise_scope :user do
      get "sessions/challenge" => "users/sessions#challenge", as: :session_challenge
      post "sessions/challenge" => "users/sessions#respond_to_challenge", as: :respond_to_session_challenge
    end

    # Registration and account management
    namespace :users do
      resources :registrations, only: [ :create ]
      get "registrations" => "registrations#new", as: :new_registration

      resources :mfa, only: [ :new, :create ]
      get "mfa/preference" => "mfa#preference", as: :mfa_preference
      post "mfa/preference" => "mfa#update_preference", as: :update_mfa_preference
      delete "mfa" => "mfa#destroy", as: :disable_mfa

      get "forgot-password" => "passwords#forgot"
      post "forgot-password" => "passwords#send_reset_password_instructions"
      get "reset-password" => "passwords#reset"
      post "reset-password" => "passwords#confirm_reset"

      get "verify-account" => "registrations#new_account_verification"
      post "verify-account" => "registrations#create_account_verification"
      post "resend-verification" => "registrations#resend_verification_code"

      get "account" => "accounts#edit"
      patch "account/email" => "accounts#update_email"
    end

    # Development-only sandbox
    namespace :dev do
      get "sandbox"
      post "send_email"
    end
  end

  # Demo tools
  get "/demo", to: "demo#index"
  namespace :demo do
    resources :certifications, only: [ :new, :create ]
  end
end

reporting-app/app/models/certification_request.rb
class CertificationRequest < ApplicationRecord
  attribute :beneficiary_id, :string
  attribute :case_number, :string

  attribute :certification_requirements, :jsonb
  attribute :beneficiary_data, :jsonb

  has_many :activity_report_application_forms

  default_scope { includes(:activity_report_application_forms) }

  # TODO: some of this should be required, but leaving it open at the moment
  # validates :beneficiary_id, presence: true

  # TODO: add validation for JSON columns (they should be hashes, etc)

  def beneficiary_account_email
    return unless self.beneficiary_data

    self.beneficiary_data.dig("account_email")
  end

  def self.find_by_beneficiary_account_email(email)
    where("beneficiary_data->>'account_email' = :email", email: email)
  end

  def beneficiary_contact_email
    return unless self.beneficiary_data

    self.beneficiary_data.dig("contact", "email")
  end

  def self.find_by_beneficiary_contact_email(email)
    where("beneficiary_data->'contact'->>'email' = :email", email: email)
  end

  def beneficiary_email
    self.beneficiary_account_email || self.beneficiary_contact_email
  end

  def self.find_by_beneficiary_email(email)
    self.find_by_beneficiary_account_email(email).or(self.find_by_beneficiary_contact_email(email))
  end
end

reporting-app/app/controllers/certification_requests_controller.rb
class CertificationRequestsController < StaffController
  before_action :set_certification_request, only: %i[ show update ]

  # GET /certifications
  # GET /certifications.json
  def index
    @certification_requests = policy_scope(CertificationRequest.all)
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
  end

  # GET /certifications/new
  def new
    @certification_request_form = authorize CertificationRequest.new
  end

  # POST /certifications
  # POST /certifications.json
  def create
    @certification_request = CertificationRequest.new(certification_request_params)

    authorize @certification_request

    if certification_service.save_new(@certification_request)
      render :show, status: :created, location: @certification_request
    else
      render json: @certification_request.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /certifications/1
  # PATCH/PUT /certifications/1.json
  def update
    if @certification_request.update(certification_request_params)
      render :show, status: :ok, location: @certification_request
    else
      render json: @certification_request.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certification_request
      @certification_request = authorize CertificationRequest.find(params[:id])
    end

    def certification_service
      CertificationRequestService.new
    end

    # Only allow a list of trusted parameters through.
    def certification_request_params
      # support both top-level params and under a "certification" key (for HTML form)
      if params&.has_key?(:certification_request)
        cert_request_params = params.fetch(:certification_request)
      else
        cert_request_params = params
      end

      cert_request_params.permit(
        :beneficiary_id,
        :case_number,
        :certification_requirements,
        :beneficiary_data,
        certification_requirements: {},
        beneficiary_data: {}
      ).tap do |cert_request_params|
        begin
          # handle HTML form input of the JSON blob as a string
          if cert_request_params[:certification_requirements].present? && cert_request_params[:certification_requirements].is_a?(String)
            cert_request_params[:certification_requirements] = JSON.parse(cert_request_params[:certification_requirements])
          end

          # handle HTML form input of the JSON blob as a string
          if cert_request_params[:beneficiary_data].present? && cert_request_params[:beneficiary_data].is_a?(String)
            cert_request_params[:beneficiary_data] = JSON.parse(cert_request_params[:beneficiary_data])
          end
        rescue JSON::ParserError => e
          raise ActionController::BadRequest.new(e.message)
        end
      end
    end
end

reporting-app/app/controllers/demo/certification_requests_controller.rb
class Demo::CertificationRequestsController < ApplicationController
  layout "demo"

  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def new
    certification_type = params.fetch(:certification_type, nil)
    certification_requirement_params = certification_service.certification_type_requirement_params(certification_type) || {}
    @form = Demo::CertificationRequests::CreateForm.new({ certification_type: certification_type }.merge(certification_requirement_params))
  end

  def create
    form_params = params.require(:demo_certification_requests_create_form).permit(:beneficiary_email, :case_number, :certification_type, :certification_date, :lookback_period, :number_of_months_to_certify, :due_period_days, :ex_parte_scenario)
    @form = Demo::CertificationRequests::CreateForm.new(form_params)

    if @form.invalid?
      flash.now[:errors] = @form.errors.full_messages
      return render :new, status: :unprocessable_entity
    end

    certification_requirements = certification_service.calculate_certification_requirements(@form.attributes.with_indifferent_access)
    beneficiary_data = {}

    case @form.ex_parte_scenario
    when "Partially met work hours requirement"
      beneficiary_data.merge!(FactoryBot.build(:certification_request_beneficiary_data, :partially_met_work_hours_requirement, cert_date: @form.certification_date))
    when "Fully met work hours requirement"
      beneficiary_data.merge!(FactoryBot.build(:certification_request_beneficiary_data, :fully_met_work_hours_requirement, cert_date: @form.certification_date, num_months: @form.number_of_months_to_certify))
    else
      # nothing
    end

    @certification_request = FactoryBot.build(
      :certification_request,
      :with_beneficiary_data_base,
      :connected_to_email,
      beneficiary_data_base: beneficiary_data,
      email: @form.beneficiary_email,
      case_number: @form.case_number,
      certification_requirements: certification_requirements,
    )

    if certification_service.save_new(@certification_request, current_user)
      redirect_to certification_request_path(@certification_request)
    else
      flash.now[:errors] = @certification_request.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  private
    def certification_service
      CertificationRequestService.new
    end
end

reporting-app/app/views/certification_requests/_form.html.erb
<%= us_form_with(model: certification_request_form, data: { turbo: false, controller: "certification_request" }) do |f| %>
  <%= f.text_field :beneficiary_id, label: t("certification_requests.beneficiary_id") %>
  <%= f.text_field :case_number, label: t("certification_requests.case_number") %>

  <%= f.text_area :certification_requirements, value: JSON.pretty_generate(certification_request_form.certification_requirements), label: t("certification_requests.certification_requirements") %>
  <%= f.text_area :beneficiary_data, value: JSON.pretty_generate(certification_request_form.beneficiary_data), label: t("certification_requests.beneficiary_data") %>

  <%= f.submit (submit_text || "Save") %>
<% end %>

reporting-app/app/views/certification_requests/index.html.erb
<% content_for :title, t(".title") %>

<h1><%= t(".title") %></h1>

<%= link_to t(".create"), new_certification_request_path(), class: "usa-button" %>

<section class="d-flex flex-column flex-md-row gap-4 align-items-start justify-content-between">
  <table class="usa-table usa-table--borderless width-full">
    <thead>
      <tr>
        <th scope="col">
          <%= t(".columns.col_certification_request_id") %>
        </th>
        <th scope="col">
          <%= t(".columns.col_case_number") %>
        </th>
        <th scope="col">
          <%= t(".columns.col_created") %>
        </th>
        <th scope="col">
          <%= t(".columns.col_actions") %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% for certification_request in @certification_requests do %>
        <tr>
          <td>
            <%= certification_request.id %>
          </td>
          <td>
            <%= certification_request.case_number %>
          </td>
          <td>
            <%= local_time(certification_request.created_at, format: :long) %>
          </td>
          <td>
              <%= link_to t(".actions.show"), certification_request_path(certification_request), class: "usa-button" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

reporting-app/app/views/certification_requests/new.html.erb
<%= render partial: "application/breadcrumbs", locals: { crumbs: [
  { name: t("certification_requests.index.title"), url: certification_requests_path },
  ], current_name: t(".title")  } %>

<% content_for :title, t(".title") %>

<h1><%= t(".title") %></h1>

<%= render "form", certification_request_form: @certification_request_form, submit_text: t(".submit") %>

reporting-app/app/views/certification_requests/show.html.erb
<%= render partial: "application/breadcrumbs", locals: { crumbs: [
  { name: t("certification_requests.index.title"), url: certification_requests_path },
  ], current_name: @certification_request.id  } %>
<% content_for :title, t(".title") %>
<h1><%= t(".title") %></h1>
<%= render "form", certification_request_form: @certification_request, submit_text: t(".submit") %>
<h2><%= t(".activity_reports.header") %></h2>
<table class="usa-table usa-table--borderless width-full">
  <thead>
    <tr>
      <th scope="col">
        <%= t(".activity_reports.col_activity_report_id") %>
      </th>
      <th scope="col">
        <%= t(".activity_reports.col_cases") %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% for activity_report in @certification_request.activity_report_application_forms do %>
      <tr>
        <td>
          <%= link_to activity_report.id, activity_report_application_form_path(activity_report) %>
        </td>
        <td>
          1
        </td>
      </tr>
    <% end %>
  </tbody>
</table>